name: lead
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.7 # Add the flutter_svg package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/onboard1.png
    - assets/onboard2.png
    - assets/onboard3.png
    - assets/onboard4.png
    - assets/google.svg

