// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7XRK0FPlz_7jyUHqj2xY8Ue_SMf9xHOg',
    appId: '1:796388366674:web:19b619d3aba6156ca8828b',
    messagingSenderId: '796388366674',
    projectId: 'lead-10402',
    authDomain: 'lead-10402.firebaseapp.com',
    storageBucket: 'lead-10402.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoo6UBnNnyfbO69aPSl7s9M3ABq3DvcZk',
    appId: '1:796388366674:android:2c0ca28370722f36a8828b',
    messagingSenderId: '796388366674',
    projectId: 'lead-10402',
    storageBucket: 'lead-10402.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo124-wPL-rOSx2Xw-brDwV5iAWagPYvw',
    appId: '1:796388366674:ios:31b011f81a6b95faa8828b',
    messagingSenderId: '796388366674',
    projectId: 'lead-10402',
    storageBucket: 'lead-10402.firebasestorage.app',
    iosBundleId: 'com.example.lead',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo124-wPL-rOSx2Xw-brDwV5iAWagPYvw',
    appId: '1:796388366674:ios:31b011f81a6b95faa8828b',
    messagingSenderId: '796388366674',
    projectId: 'lead-10402',
    storageBucket: 'lead-10402.firebasestorage.app',
    iosBundleId: 'com.example.lead',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7XRK0FPlz_7jyUHqj2xY8Ue_SMf9xHOg',
    appId: '1:796388366674:web:19b619d3aba6156ca8828b',
    messagingSenderId: '796388366674',
    projectId: 'lead-10402',
    authDomain: 'lead-10402.firebaseapp.com',
    storageBucket: 'lead-10402.firebasestorage.app',
  );
}
